// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjXV-iqSUnheO6qlC8s2Ge0ZwG_ZoaFpA',
    appId: '1:1070202927064:web:6aaf0f1f12ecea1ef4a4ad',
    messagingSenderId: '1070202927064',
    projectId: 'my-notes-db644',
    authDomain: 'my-notes-db644.firebaseapp.com',
    storageBucket: 'my-notes-db644.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCivV-j1M3IxTIlPsu1SWARkgCnY2NcCfQ',
    appId: '1:1070202927064:android:9e4b9e8328333417f4a4ad',
    messagingSenderId: '1070202927064',
    projectId: 'my-notes-db644',
    storageBucket: 'my-notes-db644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbJdoxqfRJHV-UqlGflbg4GXJOy-8GYsw',
    appId: '1:1070202927064:ios:dea007d5c5656408f4a4ad',
    messagingSenderId: '1070202927064',
    projectId: 'my-notes-db644',
    storageBucket: 'my-notes-db644.appspot.com',
    iosClientId: '1070202927064-h0j83qi3g5uofh8m0ff2glh0tne7advb.apps.googleusercontent.com',
    iosBundleId: 'org.datum.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbJdoxqfRJHV-UqlGflbg4GXJOy-8GYsw',
    appId: '1:1070202927064:ios:dea007d5c5656408f4a4ad',
    messagingSenderId: '1070202927064',
    projectId: 'my-notes-db644',
    storageBucket: 'my-notes-db644.appspot.com',
    iosClientId: '1070202927064-h0j83qi3g5uofh8m0ff2glh0tne7advb.apps.googleusercontent.com',
    iosBundleId: 'org.datum.mynotes',
  );
}
